Editor's Update status-of-this-document.md
w3c/wcag2ict pull request #344
Opened 2024-04-22 16:21 UTC by ChrisLoiselle

Editor's update to status of document aligning WCAG mentions with WCAG 2.1 and WCAG 2.2 and removing "new" as a phrase when mentioning WCAG SCs.

2024-04-22 21:32 UTC, maryjom commented
@ChrisLoiselle Since this section is meant to focus the document readers in on what to review and the intent for the publication, I've modified this section to call out the major changes since the last publication in August 2023.

2024-04-23 16:31 UTC, daniel-montalvo requested changes

2024-04-23 16:31 UTC, daniel-montalvo commented on status-of-this-document.md
> +Once public comments submitted for this publication of the WCAG2ICT Draft Working Group Note are addressed, the intent is for the next publication of this document to be a finalized W3C Working Group
```suggestion
This is the planned last draft before we publish this as a W3C Working Group Note.

</div>
```

2024-05-02 13:32 UTC, pday1 approved these changes

2024-05-13 21:13 UTC, maryjom submitted a review, later dismissed

2024-05-13 21:15 UTC, maryjom commented
@daniel-montalvo Not sure, but I think you need to re-review?  It says merging is blocked. I pulled in your suggested changes.

2024-05-13 21:23 UTC, maryjom approved these changes

2024-05-14 08:22 UTC, pday1 approved these changes

2024-05-14 10:49 UTC, daniel-montalvo submitted a review, later dismissed

2024-05-14 10:55 UTC, maryjom approved these changes

2024-05-14 10:55 UTC, merged

2024-05-14 10:55 UTC, daniel-montalvo approved these changes