Clean up old editors' notes
w3c/wcag2ict pull request #350
Opened 2024-04-30 21:27 UTC by maryjom

2024-05-03 08:38 UTC, pday1 requested changes
All good apart from a typo in one of the notes
 ### Comparison with the 2013 WCAG2ICT Note

"fromg" -> "from"

2024-05-03 08:38 UTC, pday1 commented on introduction.md
> +<p class="ednote">In this publication WCAG2ICT Task Force has incorporated all of the new WCAG 2.2 success criteria and glossary terms and addressed public comments fromg the First Public Working Dra
Typo: change "fromg" to "from"

2024-05-08 12:38 UTC, pday1 approved these changes
Approve with changes that I added

2024-05-09 11:45 UTC, ChrisLoiselle approved these changes

2024-05-14 04:39 UTC, merged