Update success-criteria-problematic-for-closed-functionality.md - Min…
w3c/wcag2ict pull request #352
Opened 2024-05-06 14:11 UTC by pday1

…or changes to SC problematic to fix inconsistencies and grammar issues

Changes proposed in SC problematic for closed:

1.4.4 Resize text
2.4.2 Page titled
3.3.1 Error identification
4.1.3 Status messages

2024-05-07 14:18 UTC, ChrisLoiselle submitted a review, later dismissed

2024-05-14 12:30 UTC, ChrisLoiselle approved these changes

2024-05-14 12:31 UTC, ChrisLoiselle approved these changes

2024-05-14 12:31 UTC, ChrisLoiselle approved these changes

2024-05-14 12:32 UTC, ChrisLoiselle approved these changes

2024-05-16 15:26 UTC, bruce-usab requested changes
Several uses of "requires" should be "depends upon" and I have concern merging to main will revert some edits from PR#348

2024-05-16 18:28 UTC, maryjom commented on success-criteria-problematic-for-closed-functionality.md
> +<li><a href="#error-identification">3.3.1 Error Identification</a> — It is important for errors that can be detected to be described to the user; for closed functionality, the error description doesn
```suggestion
<li><a href="#error-identification">3.3.1 Error Identification</a> — It is important for errors that can be detected to be described to the user; for ICT with closed functionality, the error description doesn’t have to be provided in text, as defined in WCAG 2.</li>
```

2024-05-16 18:31 UTC, maryjom commented
> Several uses of "requires" should be "depends upon" and I have concern merging to main will revert some edits from PR#348

FYI Bruce, I'll be manually merging your text changes into Phil's to combine in the appropriate edits.

2024-05-16 19:02 UTC, maryjom approved these changes

2024-05-16 19:03 UTC, ChrisLoiselle approved these changes

2024-05-16 19:04 UTC, merged